# Site settings
title: iBeacons

email: daniel-schofield93@hotmail.com

description: > # this means to ignore newlines until "baseurl:"
  Bluetooth Beacons
baseurl: "/iBeacons" # the subpath of your site, e.g. /blog
#url: "https://schoballs.github.io" # the base hostname & protocol for your site



# Build settings
markdown: kramdown
